server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:postgresql://localhost:5432/zsljgx
      username: postgres
      password: 'dys123!@#'
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappings/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.net.gddh.qrcode.entity  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql